init
update dataset discription

add Nonstationary_Transformer and corresponding scripts

add PatchTST and corresponding scripts

ETSformer and Pyraformer

Update README.md

Rename pyraformer file

Update README.md

Update README.md

update framework

update framework

Update requirements.txt

update requirements

Update README.md

Update README.md

Update README.md

Updata README.md

Update TimesNet.py

Update TimesNet.py

Update requirements.txt

Update requirements.txt

add MICN and corresponding scripts

add MICN and corresponding scripts

Update README.md

Add Pyraformer and scipts

Update README.md

Update README.md

Update SelfAttention_Family.py

Update FourierCorrelation.py

Update MultiWaveletCorrelation.py

Update FEDformer.py

Update requirements.txt

Improve baseline results

Update TimesNet.sh

add Crossformer and corresponding scripts

Update FourierCorrelation.py

Update README.md

Update README.md

Update README.md

Update run.py

Update run.py

add Crossformer and corresponding scripts

fix the model of PatchTST

Update README.md

Update run.py

add FiLM and corresponding scripts

Add dataset

Fix TimesNet bash

Fix some errors

Fix function call

Remove some prints

Add version for requirements

Add some comments to clarify

Update requirements.txt

clean

refine script

clean

Update FEDformer.py

proper attribution for time features

Update README.md

Delete seq_len

Correct annotation errors

Improve annotations

Update README.md

Update TimesNet_M4.sh

Improve annotations

Update README.md

Update TimesNet_ETTh1.sh

Update MICN_ETTh1.sh

Update MICN_ETTh2.sh

Update README.md

Update README.md

Update README.md

Bug Fix: ECL_script/Nonstationary_Transformer.sh

  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \

Bug Fix: ECL_script/Transformer.sh

  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \

Fix error: Traffic/Transformer.sh

  --enc_in  862 \
  --dec_in  862 \
  --c_out 862 \

upload tutorial

small bug fixed

Update README.md

Update README.md

Update README.md

Update data_loader.py

fixed --inverse

fixed --inverse

update tutorial about timeF encoding

update tutorial about timeF encoding

Official implementation of iTransformer added

Official implementation of iTransformer added

Official implementation of iTransformer added

Update README.md

Update README.md

Update README.md

Official implementation of iTransformer added

standardize the naming and annotation of the code

Update iTransformer_ETTh2.sh to match the dims of ETT dataset

Fix typo in README.md

leaderborad -> leaderboard

Updated README.md

Update README.md

Removed Grammatical Errors and punctuation marks error.

Update README.md

docs: fix and improve content in tutorial/TimesNet_tutorial.ipynb

Update README.md

Update README.md

added full_stops

add n_heads for FEDformer

fix MS inverse

Update README.md

Update README.md

add Koopa

Delete checkpoints directory

Update README.md

Update TimesNet_ETTh1.sh

Updated Contributors Section

Fixed #250

fix MS inverse

Delete .DS_Store

Update README.md

Update README.md

Update MICN.sh

add TiDE and its ETTh1 script

add imputation to TiDE

add imputation to TiDE

Update README.md

Format console args print

capitalization

[bug-fix] Values of args are not actual while printing in console.

Update README.md

fix typos

Update Nonstationary_Transformer.sh

added FreTS model

Update exp_basic.py with FreTS model

Update run.py with channel_independence config for FreTS model

refactored FreTS model to match the TSlib's Model API

Update README.md

fix KPLayer in Koopa.py

Update README.md

added mamba model

https://arxiv.org/abs/2312.00752

Hardware Aware Mamba + Long Term Forecasting

removed tee from mamba all script

Update README.md

Update README.md

fix bugs in imputation for MS

add=add TimeMixer and TSMixer

add=add TimeMixer and TSMixer

add=add TimeMixer and TSMixer

Update README.md

Update README.md

Update README.md

Update README.md

Add SegRNN Code

Add implementation code of SegRNN, a powerful time series forecating model based on recurrent neural networks

Update README.md

comments cleanup

Update README.md

Update README.md

dtw metric added

dtw metric added

ADF metric implemented

augmentation batch

Update data_factory.py

aug code formalization

augmentation classification

revisions

requirement revise

Delete run_anylearn.py

fixed model_name to FEDformer in ECL_script

Remove redundant code from data_factory.py

add TemporalFusionTransformer

add SCINet

add SCINet

add SCINet

add SCINet

Update README.md

correct the normalization in PatchTST

Update README.md

Update TimeMixer.py

Update data_factory.py

Update README.md

Update README.md

Update README.md

Update exp_long_term_forecasting.py

Update MambaSimple.py

Update exp_basic.py

Fix mamba install problem

Fix the inverse operation in long-term forecasting

Fix classification task

Update README.md

Update README.md

remove act and dropout for dlinear's classification

use true - pred in M*E

Update TimeMixer.py

fixed data_factory.py which will shuffle test dataset for classification task

ConvBlock: fix inception v2 kernel number to reslist size mapping

Made CONTRIBUTING.md

Update CONTRIBUTING.md

Update CONTRIBUTING.md

Update CONTRIBUTING.md

Update README.md

Update TimesNet.sh

Fix Monthly split for M4 Comp

Due to a sample size missmatch we need to define the dtype explicitly

Update data_loader.py

docs: update README.md

sequenctial -> sequential

Update requirements.txt

einsum is not available in 0.4.0

Update README.md

Update README.md

fix bugs according to issues #529 #516

fix bugs according to issues #529 #516

fix bugs according to issues #524

fix bugs according to issues #534 #535

clean

Update README.md

quotation error

Update exp_long_term_forecasting.py

Update run.py

Update print_args.py

remove output attention

add method PAttn

Update README.md

Update README.md

add TimeXer

Update TimeXer.py

Update TimeXer.py

update exogenous scripts

fix typos

Update README.md

Update README.md

Update README.md

Update README.md

Changes

Update exp_long_term_forecasting.py

mps support

fixed hardcoded cuda bug

Update exp_long_term_forecasting.py

Update run.py

Update data_loader.py

Update run.py

adding WPMixer

adding WPMixer

updating WPMixer

add WPMixer according to pr#645

change WPMixer to fit TSLib

Update README.md

fix:solve the error when run the command "python ./run.py  --help"
error is :…………
return self._get_help_string(action) % params
ValueError: unsupported format character ')' (0x29) at index 22

Create MultiPatchFormer.py

Create Electricity.sh

Create Traffic.sh

Create ETTh1.sh

Create ETTm1.sh

Create Weather.sh

add MultiPatchFormer model

add MultiPatchFormer model

Update README.md

Update README.md

Fix the problem of negative indices in M4 outsample_window

Update tools.py

fix: prevent in-place operations in TimesNet model to avoid potential side effects

fix:remove output_attention from MultiPatchFormer.py according to issues#727

fix bugs according to issues #730 #732

fix typos in TImesNet.py

fix bugs according to issues #735 #736